import play.sbt.routes.RoutesKeys
import scoverage.ScoverageKeys
import uk.gov.hmrc.DefaultBuildSettings

val appName = "economic-crime-levy-account"

ThisBuild / scalaVersion := "3.3.7"
ThisBuild / majorVersion := 0

lazy val app = (project in file("."))
  .enablePlugins(PlayScala, SbtDistributablesPlugin)
  .disablePlugins(JUnitXmlReportPlugin) //Required to prevent https://github.com/scalatest/scalatest/issues/1427
  .settings(testSettings*)
  .settings(inThisBuild(buildSettings))
  .settings(scoverageSettings*)
  .settings(scalaCompilerOptions*)
  .settings(
    Compile / unmanagedResourceDirectories += baseDirectory.value / "resources",
    Compile / unmanagedResourceDirectories += baseDirectory.value / "../conf"
  )
  .settings(
    name := appName,
    RoutesKeys.routesImport ++= Seq(
      "uk.gov.hmrc.play.bootstrap.binders.RedirectUrl"
    ),
    PlayKeys.playDefaultPort := 14009,
    libraryDependencies ++= AppDependencies(),
    excludeDependencies += ExclusionRule("org.lz4", "lz4-java"),
    retrieveManaged := true,
    (update / evictionWarningOptions).withRank(KeyRanks.Invisible) :=
      EvictionWarningOptions.default.withWarnScalaVersionEviction(false)
  )

lazy val root: Project = (project in file("."))
  .aggregate(app, it)

lazy val buildSettings = Def.settings(
  scalafmtOnCompile := true,
  useSuperShell := false
)

lazy val testSettings: Seq[Def.Setting[?]] = Seq(
  Test / unmanagedSourceDirectories := Seq(
    baseDirectory.value / "test",
    baseDirectory.value / "test-common"
  ),
  Test / fork := true
)

lazy val it = (project in file("it"))
  .enablePlugins(PlayScala)
  .dependsOn(app % "compile->compile;test->test")
  .settings(
    DefaultBuildSettings.itSettings(),
    libraryDependencies ++= AppDependencies.itDependencies,

    Test / unmanagedSourceDirectories := Seq(
      baseDirectory.value / "test",
      baseDirectory.value / "test-common"
    ),

    Test / fork := true,
    Test / parallelExecution := false
  )

val excludedScoveragePackages: Seq[String] = Seq(
  "<empty>",
  "Reverse.*",
  ".*handlers.*",
  "uk.gov.hmrc.BuildInfo",
  "app.*",
  "prod.*",
  ".*Routes.*",
  ".*testonly.*",
  "testOnlyDoNotUseInAppConf.*",
  "uk.gov.hmrc.economiccrimelevyaccount.connectors.httpParsers.*"
)

val scoverageSettings: Seq[Setting[?]] = Seq(
  ScoverageKeys.coverageExcludedFiles := excludedScoveragePackages.mkString(";"),
  ScoverageKeys.coverageMinimumStmtTotal := 90,
  ScoverageKeys.coverageFailOnMinimum := true,
  ScoverageKeys.coverageHighlighting := true
)

val scalaCompilerOptions: Def.Setting[Task[Seq[String]]] = scalacOptions ++= Seq(
  // Play routes-generated Scala
  "-Wconf:msg=unused import&src=.*/conf/.*:s",
  "-Wconf:msg=unused import&src=.*/routes/.*:s",

  // Silence unused pattern variables from Play routes
  "-Wconf:msg=unused pattern variable&src=.*/conf/.*:s",
  "-Wconf:msg=unused pattern variable&src=.*/routes/.*:s",

  // Silence unused private members generated by Play routes includes
  "-Wconf:msg=unused private member&src=.*/conf/.*:s",
  "-Wconf:msg=unused private member&src=.*/routes/.*:s",

  "-feature"
)
addCommandAlias("runAllChecks", ";clean;compile;scalafmtCheckAll;coverage;test;it:test;scalastyle;coverageReport")
